// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhtgQxwWlwQ9RstTNUQyqnV2bPjuA8zJI',
    appId: '1:419036976717:web:37fbd374c0a473d8762e04',
    messagingSenderId: '419036976717',
    projectId: 'expense-tracker-1e6ee',
    authDomain: 'expense-tracker-1e6ee.firebaseapp.com',
    storageBucket: 'expense-tracker-1e6ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Kb4Gb2-U29unfXpIlkJao42SxK9_O1s',
    appId: '1:419036976717:android:e6e324b0fdb80ac3762e04',
    messagingSenderId: '419036976717',
    projectId: 'expense-tracker-1e6ee',
    storageBucket: 'expense-tracker-1e6ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3R0y6x6TgYDiPtnK7dmKn0WQn2CfHBY',
    appId: '1:419036976717:ios:02a90c24607db95e762e04',
    messagingSenderId: '419036976717',
    projectId: 'expense-tracker-1e6ee',
    storageBucket: 'expense-tracker-1e6ee.firebasestorage.app',
    iosBundleId: 'com.ovibbo.expensetracker.expenseTracker',
  );
}
